### ISSUE TITLE
Can't launch the project: bundling failed: UnableToResolveError: Unable to resolve module `buffer`

### ISSUE THREAD

**Issue by manifoldhiker** [elmish/sample-rn-counter#2]
## Expected Behavior

Fresh project builds and launches normally

## Current Behavior

Build crashes on the bundling stage

## Steps to Reproduce

1. Clone the repository
2. Launch fresh android emulator (Nexus_5X_API_28) from Android studio
3. Open the first terminal:
    1 `cd sample-rn-counter`
    2. `yarn`
    3. `cd ./src`
    4. `dotnet restore`
    5. `dotnet fable yarn-watch`
4. Open the second terminal:
    1 `cd sample-rn-counter`
    2. `react-native run-android`

## Context (Environment)

OS: Windows 10
Shell: PowerShell

## Output
```
Scanning folders for symlinks in D:\programming\test\react-native-counter\sample-rn-counter\node_modules (20ms)
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running Metro Bundler on port 8081.                                       │
 │                                                                            │
 │  Keep Metro Bundler running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own Metro Bundler  instance if you    │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   D:\programming\test\react-native-counter\sample-rn-counter


Metro Bundler ready.

Loading dependency graph, done.
Bundling `index.js`  [development, non-minified]  98.3% (816/823), failed.
error: bundling failed: UnableToResolveError: Unable to resolve module `buffer` from `D:\programming\test\react-native-counter\sample-rn-counter\out\fable\Fable.Helpers.ReactNative.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ModuleResolver.resolveNodeDependency (D:\programming\test\react-native-counter\sample-rn-counter\node_modules\metro-bundler\src\node-haste\DependencyGraph\ModuleResolution.js:292:11)
    at ModuleResolution.tryResolveSync (D:\programming\test\react-native-counter\sample-rn-counter\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:103:16)
    at Object.tryResolveSync (D:\programming\test\react-native-counter\sample-rn-counter\node_modules\metro-bundler\src\node-haste\DependencyGraph\ModuleResolution.js:118:12)
    at ResolutionRequest.resolveDependency (D:\programming\test\react-native-counter\sample-rn-counter\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:100:39)
    at dependencyNames.map.name (D:\programming\test\react-native-counter\sample-rn-counter\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:134:10)
    at Array.map (<anonymous>)
    at ResolutionRequest.resolveModuleDependencies (D:\programming\test\react-native-counter\sample-rn-counter\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:133:42)
    at module.readFresh.then (D:\programming\test\react-native-counter\sample-rn-counter\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:181:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
![Emulator screenshot](https://image.prntscr.com/image/_QvjzZz_Sg2ZzofXw2zHRw.png)

**Comment by et1975** [comment]
I must have accidentally removed that dependency, but since it was in my `node_modules` my bundling still worked. 
Fixed and Thank you!
